services:
  - type: web
    name: festival-ecommerce
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn festival_ecommerce.wsgi:application"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: PYTHON_VERSION
        value: 3.12.3
      - key: DATABASE_URL
        fromDatabase:
          name: festival-ecommerce-db
          property: connectionString

databases:
  - name: festival-ecommerce-db
    databaseName: festival_ecommerce
    user: festival_user
    plan: free
